spring:
  application:
    name: paynow-agent-assist
  
  # These values should be updated for a production deployment for demonstration purposes using profile with h2 configuration
  datasource:
    url: ${DATABASE_URL:jdbc:h2:file:./data/paynow_prod;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}  # For demo - use 'validate' in real production
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        # dialect: org.hibernate.dialect.PostgreSQLDialect  # Uncomment for PostgreSQL
  
  h2:
    console:
      enabled: false  # Disable H2 console in production
  
  cache:
    type: simple  # Use simple cache for demo - change to 'redis' for production

# Production security settings
server:
  port: ${PORT:8080}
  ssl:
    enabled: ${SSL_ENABLED:false}
  servlet:
    session:
      timeout: 30m
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: true

logging:
  level:
    com.paynow.agentassist: INFO
    org.springframework.security: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId}] %logger{36} - %msg%n"
  file:
    name: /var/log/paynow/application.log
    max-size: 100MB
    max-history: 30

# Production-specific configuration
paynow:
  # NO API KEYS IN PRODUCTION CONFIG - These should be in the database
  rate-limit:
    requests-per-second: 100
    bucket-capacity: 200
  agent:
    max-retries: 3
    timeout-seconds: 15
