spring:
  application:
    name: paynow-agent-assist
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  cache:
    type: simple

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.paynow.agentassist: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{requestId}] %logger{36} - %msg%n"

# Local development API keys - automatically initialized by DataInitializer
paynow:
  security:
    api-keys:
      - key: "paynow-api-key-test"
        name: "api-client"
        description: "API access for payment decisions"
        userId: "user1"
      - key: "another-api-key-for-testing"
        name: "test-client"
        description: "Another API key for testing"
        userId: "user2"
  rate-limit:
    requests-per-second: 5
    bucket-capacity: 10
  agent:
    max-retries: 2
    timeout-seconds: 30